//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONT_PAISES
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TONT_PAISES()
        {
            this.TONT_AVES = new HashSet<TONT_AVES>();
        }
    
        public string CDPAIS { get; set; }
        public string DSNOMBRE { get; set; }
        public string CDZONA { get; set; }
    
        public virtual TONT_ZONAS TONT_ZONAS { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONT_AVES> TONT_AVES { get; set; }
    }
}
