//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaCRUD.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TONT_ZONAS
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TONT_ZONAS()
        {
            this.TONT_PAISES = new HashSet<TONT_PAISES>();
        }
    
        public string CDZONA { get; set; }
        public string DSNOMBRE { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TONT_PAISES> TONT_PAISES { get; set; }
    }
}
